modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
issueTrackerURL = "https://github.com/MoonflowerTeam/${archives_base_name}/issues"
license = "GPLv3"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
logoFile = "${mod_id}.logo.png"
authors = "Moonflower"
credits = "Ocelot, Jackson, Farcr (Art), AstraZoey (Sound Design)"
displayURL = "https://www.moonflower.gg"

[modproperties.${ mod_id }]
catalogueImageIcon = "${mod_id}.icon.png"

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "AFTER"
side = "BOTH"